### ISSUE TITLE
Error importing datepicker with npm install ng2-datepicker

### ISSUE THREAD

**Issue by matstank** [jkuri/ng2-datepicker#4]
I installed the datepicker with ng2-datepicker.
That went successfully and added ng2-datepicker in the node_modules folder. 

import {DatePicker} didn't cause any errors.
But as soon as I add DatePicker into 'directives: [DatePicker]'
my app does not load and gives error:

Uncaught SyntaxError: Unexpected token <  ng-datepicker:1

**Comment by jkuri** [comment]
Are you using SystemJS loader?

**Comment by matstank** [comment]
I am using SystemJS loader in my app, but did not want to use it for DatePicker. 
This may be a problem for me though, and it looks like an issue might also be that since I am also not including moment in the SystemJS loader that ng2-datepicker is also unable to import moment.

**Comment by jkuri** [comment]
Yes, that might be an issue. Please try including `ng2-datepicker` as I wrote in the readme.. If that won't work, I can prepare standalone `.js` file which can be included as `<script src="...."></script>`.

**Comment by matstank** [comment]
Adding moment and ng2-datepicker into systemjs loader corrected the issues.
The readme does not note that this is a required step and also has an example with ng2-slimscroll instead of datepicker. 

It would be very nice if this component could just be imported in the standard angular2 way with 
" import {DatePicker} from 'node_modules/ng2-datepicker' " without having to alter systemjs loader with this and with moment. 

Otherwise, well done and thanks for the component.

**Comment by jkuri** [comment]
Thanks for noticing error in readme, I fixed it. No problem, glad you find it useful.

**Comment by largeDachshund** [comment]
Jan,
thanks again for your work on this library.  i'm new to all these build tools.  if i'm using webpack, i'm getting a reference error because the .js uses System.*

Do I have to abandon webpack for SystemJS to use your application in my application?  

Thanks,

**Comment by jkuri** [comment]
Actually I never tried to use webpack so I can't give you an answer. This components bundle is configured to work with SystemJS and is also compatible with the official [Angular CLI](https://github.com/angular/angular-cli/blob/master/docs/ng-install.md) install command.

**Comment by deshazer72** [comment]
matstank can you provide example of what you did to make this work.. I am getting 404 not found from node modules. I am not using system.js I am using system.config.js provided by angular quickstart. I tried adding ng2-datepicker: npm:ng2-datepicker to that file and moment but still getting the error.

**Comment by rrohitesh** [comment]
@jkuri @deshazer72 @largeDachshund 
I am using this date picker with webpack and it goes well if i use 1.4.x version but as soon as i update my version during webpack build i am getting this error:

```
ERROR in js/app.91f246157135884dd7d1.js from UglifyJs
SyntaxError: Unexpected token: punc ({) [./~/ng2-datepicker/lib-dist/ng2-datepicker.module.js:1,0]
```

is this problem with datepicker or i need to configure differently for webpack?
